-- Create the customers table
CREATE TABLE DBS211_customers (
    CUSTOMERNUMBER NUMBER PRIMARY KEY,
    CUSTOMERNAME VARCHAR2(50),
    CONTACTLASTNAME VARCHAR2(50),
    CONTACTFIRSTNAME VARCHAR2(50),
    PHONE VARCHAR2(50),
    ADDRESSLINE1 VARCHAR2(50),
    ADDRESSLINE2 VARCHAR2(50),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    POSTALCODE VARCHAR2(15),
    COUNTRY VARCHAR2(50),
    SALESREPEMPLOYEENUMBER VARCHAR2(50),
    CREDITLIMIT NUMBER
);

-- Create the orders table
CREATE TABLE DBS211_orders (
    ORDERNUMBER NUMBER PRIMARY KEY,
    ORDERDATE DATE,
    REQUIREDDATE DATE,
    SHIPPEDDATE DATE,
    STATUS VARCHAR2(15),
    COMMENTS VARCHAR2(200),
    CUSTOMERNUMBER NUMBER,
    FOREIGN KEY (CUSTOMERNUMBER) REFERENCES DBS211_customers(CUSTOMERNUMBER)
);

-- Create the order details table
CREATE TABLE DBS211_orderdetails (
    ORDERNUMBER NUMBER,
    PRODUCTCODE VARCHAR2(15),
    QUANTITYORDERED NUMBER,
    PRICEEACH NUMBER,
    ORDERLINENUMBER NUMBER,
    PRIMARY KEY (ORDERNUMBER, PRODUCTCODE),
    FOREIGN KEY (ORDERNUMBER) REFERENCES DBS211_orders(ORDERNUMBER)
);

-- Create the products table
CREATE TABLE DBS211_products (
    PRODUCTCODE VARCHAR2(15) PRIMARY KEY,
    PRODUCTNAME VARCHAR2(50),
    PRODUCTLINE VARCHAR2(50),
    PRODUCTVENDOR VARCHAR2(50),
    PRODUCTDESCRIPTION VARCHAR2(255),
    QUANTITYINSTOCK NUMBER,
    BUYPRICE NUMBER,
    MSRP NUMBER
);

-- Query to find customer by ID
SELECT * FROM DBS211_customers WHERE CUSTOMERNUMBER = :customerId;

-- Query to find customer by name
SELECT * FROM DBS211_customers WHERE CUSTOMERNAME = :customerName;

-- Customer report query by name
SELECT C.CONTACTFIRSTNAME, C.CONTACTLASTNAME, O.CUSTOMERNUMBER, O.ORDERNUMBER, P.PRODUCTNAME
FROM DBS211_CUSTOMERS C
JOIN DBS211_ORDERS O ON C.CUSTOMERNUMBER = O.CUSTOMERNUMBER
JOIN DBS211_ORDERDETAILS OD ON O.ORDERNUMBER = OD.ORDERNUMBER
JOIN DBS211_PRODUCTS P ON OD.PRODUCTCODE = P.PRODUCTCODE
WHERE C.CUSTOMERNAME = :customerName;

-- Customer report query by ID
SELECT C.CONTACTFIRSTNAME, C.CONTACTLASTNAME, O.CUSTOMERNUMBER, O.ORDERNUMBER, P.PRODUCTNAME
FROM DBS211_CUSTOMERS C
JOIN DBS211_ORDERS O ON C.CUSTOMERNUMBER = O.CUSTOMERNUMBER
JOIN DBS211_ORDERDETAILS OD ON O.ORDERNUMBER = OD.ORDERNUMBER
JOIN DBS211_PRODUCTS P ON OD.PRODUCTCODE = P.PRODUCTCODE
WHERE C.CUSTOMERNUMBER = :customerId;

-- Insert new customer
INSERT INTO DBS211_customers (CUSTOMERNUMBER, CUSTOMERNAME, CONTACTLASTNAME, CONTACTFIRSTNAME, PHONE, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, SALESREPEMPLOYEENUMBER, CREDITLIMIT)
VALUES (:customerNumber, :customerName, :contactLastName, :contactFirstName, :phone, :addressLine1, :addressLine2, :city, :state, :postalCode, :country, :salesRepEmployeeNumber, :creditLimit);

-- Update customer
UPDATE DBS211_customers SET :columnName = :newValue WHERE CUSTOMERNUMBER = :customerNumber;

-- Remove customer
DELETE FROM DBS211_customers WHERE CUSTOMERNUMBER = :customerNumber;
